import os
import collections
import pandas as pd
import configparser

# Load configuration
config = configparser.ConfigParser()
config.read('config.ini')

# Get paths from config
base_path = config['categorization']['base_path']
all_features_file = os.path.join(base_path, config['categorization']['all_features_file'])
categories_file = config['categorization']['feature_categories_file']

# Columns that are metadata rather than measured features
metadata_columns = [c.strip() for c in config['categorization']['metadata_columns'].split(',') if c.strip()]

# Step 1: Rules for guessing the category and the organelle from a feature name.
# CellProfiler encodes both axes in the name: the measurement module follows the
# rp_norm_ prefix, and the organelle follows from the stain channel when there is one
# (Intensity, Granularity, RadialDistribution, Texture) or from the measured object
# otherwise (AreaShape, counts). Colocalization features span two channels by
# definition, so they are not attributable to a single organelle.
CHANNELS = {'GrayLys': 'Lysosomes', 'GrayMito': 'Mitochondria', 'GrayNuclei': 'Nuclei'}
OBJECTS = {'RelateLysoCell': 'Lysosomes', 'RelateMitoCell': 'Mitochondria',
           'FilteredNuclei': 'Nuclei', 'Cells': 'Other', 'Cytoplasm': 'Other'}
SPAN_CHANNELS = ('Correlation',)


def guess_category(feature):
    if feature.startswith('counts_'):
        return 'Counts'
    if feature.startswith('rp_norm_'):
        token = feature[len('rp_norm_'):].split('_')[0]
        # rp_norm_Mean_PunctaLyso_* are lysosome-puncta relationship measurements
        return 'Correlation' if token == 'Mean' else token
    return ''


def guess_organelle(feature, category):
    if category in SPAN_CHANNELS:
        return 'Other'
    parts = feature.split('_')
    for part in parts:                      # the stain channel wins when present
        if part in CHANNELS:
            return CHANNELS[part]
    for part in reversed(parts):            # otherwise the measured object
        if part in OBJECTS:
            return OBJECTS[part]
    return ''


# Step 2: Read the full feature list from the header of a pooled/standardized table.
# Read the header line directly rather than through pandas, which silently renames
# duplicated columns ('x' and 'x.1') and would add the renamed one as a new feature.
with open(all_features_file) as fh:
    header = [c.strip() for c in fh.readline().rstrip('\n').split('\t')]

duplicated = sorted({c for c, n in collections.Counter(header).items() if c and n > 1})
if duplicated:
    print(f"WARNING: {len(duplicated)} column name(s) appear more than once in the header "
          f"and were read once each: {', '.join(duplicated)}")

features = sorted({c for c in header if c and c not in metadata_columns})
print(f"Read {len(features)} features from {all_features_file}")

# Step 3: Keep every assignment already in the table - it may have been corrected by
# hand - and only guess for features that are not in it yet
existing = {}
if os.path.exists(categories_file):
    current = pd.read_csv(categories_file, sep='\t', comment='#', dtype=str).fillna('')
    existing = {r.feature: (r.category, r.organelle) for r in current.itertuples()}
    print(f"Loaded {len(existing)} existing assignments from {categories_file}")

rows, added, unresolved = [], 0, []
for feature in features:
    if feature in existing:
        category, organelle = existing[feature]
    else:
        category = guess_category(feature)
        organelle = guess_organelle(feature, category)
        added += 1
        if not category or not organelle:
            unresolved.append(feature)
    rows.append((feature, category, organelle))

# Features already in the table but absent from this run's input are kept, so the
# lookup stays valid across experiments that measure different feature sets
for feature, (category, organelle) in existing.items():
    if feature not in set(features):
        rows.append((feature, category, organelle))

rows.sort()

# Step 4: Write the table back out, preserving the comment header
header = [
    "# Universal feature categorization for the HCS-proc pipeline.",
    "# One row per CellProfiler feature: the measurement category and the organelle it",
    "# describes. Generated by build_feature_categories.py from the header of a pooled",
    "# feature table, then corrected by hand where the name is ambiguous.",
    "#",
    "# Rerunning the script never overwrites a row that is already here - it only appends",
    "# features it has not seen. Edit assignments in place; blank means undecided, and a",
    "# blank row is reported by count_feature_types.py rather than silently dropped.",
    "#",
    "# category  : Counts, AreaShape, Granularity, Intensity, RadialDistribution,",
    "#             Texture, Correlation, Number",
    "# organelle : Nuclei, Lysosomes, Mitochondria, Other",
]
with open(categories_file, 'w', newline='\n') as fh:
    fh.write('\n'.join(header) + '\n')
    fh.write('feature\tcategory\torganelle\n')
    for feature, category, organelle in rows:
        fh.write(f'{feature}\t{category}\t{organelle}\n')

print(f"Wrote {len(rows)} features to {categories_file} ({added} newly added)")
if unresolved:
    print(f"{len(unresolved)} feature(s) could not be assigned - fill these in by hand:")
    for feature in unresolved:
        print(f"  {feature}")
